# Generated by Django 4.1.3 on 2022-12-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарии о водителе'},
        ),
    ]
