# Generated by Django 4.1.3 on 2022-12-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_options'),
        ('comment', '0004_alter_comment_options_remove_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
            preserve_default=False,
        ),
    ]
