# Generated by Django 4.1.3 on 2022-12-06 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0005_comment_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default='  ', max_length=1000, verbose_name='комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
