# Generated by Django 4.1.3 on 2022-12-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_person_options_and_more'),
        ('comment', '0006_alter_comment_options_remove_comment_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
