# Generated by Django 4.1.3 on 2022-12-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_person_options_and_more'),
        ('comment', '0007_alter_comment_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='водитель'),
        ),
    ]
