# Generated by Django 4.1.3 on 2022-12-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0002_alter_raiting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raiting',
            options={'verbose_name': 'raiting'},
        ),
    ]
