# Generated by Django 4.1.3 on 2022-12-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0004_alter_raiting_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raiting',
            options={'verbose_name': 'Рейтинг.'},
        ),
        migrations.RenameField(
            model_name='raiting',
            old_name='category',
            new_name='name',
        ),
    ]
