# Generated by Django 4.1.3 on 2022-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0005_alter_raiting_options_rename_category_raiting_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raiting',
            options={'ordering': ('-id',), 'verbose_name': 'рейтинг', 'verbose_name_plural': 'рейтинг'},
        ),
        migrations.AlterField(
            model_name='raiting',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Категория'),
        ),
    ]
