# Generated by Django 4.1.3 on 2022-12-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person'},
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=24, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=24, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='license',
            field=models.CharField(max_length=12, verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_name',
            field=models.CharField(max_length=24, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
    ]
