# Generated by Django 4.1.3 on 2022-12-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0004_alter_raiting_category'),
        ('person', '0003_alter_person_options_alter_person_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='raiting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raiting.raiting'),
            preserve_default=False,
        ),
    ]
