# Generated by Django 4.1.3 on 2022-12-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_raiting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персональные данные водителя.'},
        ),
    ]
