# Generated by Django 4.1.3 on 2022-12-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0006_alter_raiting_options_alter_raiting_name'),
        ('person', '0005_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-id',), 'verbose_name': 'водитель', 'verbose_name_plural': 'водители'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='license',
            field=models.CharField(max_length=32, verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_name',
            field=models.CharField(max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='raiting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiting.raiting', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
