# Generated by Django 4.1.3 on 2022-12-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0006_alter_raiting_options_alter_raiting_name'),
        ('person', '0006_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='raiting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='raiting.raiting', verbose_name='Рейтинг'),
        ),
    ]
