# Generated by Django 4.1.3 on 2022-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_person_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='license',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Номер водительского удостоверения'),
        ),
    ]
