# Generated by Django 4.1.3 on 2022-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_person_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='footnote',
            field=models.FileField(default=1, upload_to='footnote/'),
            preserve_default=False,
        ),
    ]
